baseURL = '/'
relativeURLs = true
languageCode = 'en-us'
title = 'オムそば丼スライドサイト'
theme = ["github.com/dzello/reveal-hugo"]
publishDir = "../dist/slides"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[[reveal_hugo.plugins]]
name = "RevealMenu"
source = "plugins/memu/menu.js"
css = "plugins/memu/menu.css"