baseURL = '/'
relativeURLs = true
languageCode = 'en-us'
title = 'オムそば丼スライドサイト'
theme = ["github.com/dzello/reveal-hugo"]
publishDir = "../dist/slides"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
